1731398872851	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1731398948617	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1731398948617	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1731398948619	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1731398948622	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1731398949679	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1731398951080	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1731398951081	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1731398951086	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1731398951087	Sync.Service	DEBUG	User-Agent: Firefox/132.0.1 (Linux x86_64) FxSync/1.134.0.20241105234603.desktop
1731398951087	Sync.Service	INFO	Starting sync at 2024-11-12 09:09:11 in browser session ktvDMXQxReH5
1731398951088	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1731398951089	Sync.Status	INFO	Resetting Status.
1731398951089	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1731398951090	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1731398951094	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/264342808/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1731398951094	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1731398951094	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1731398951095	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1731398951095	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1731398951097	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
